extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - import
parserOptions:
  project:
    - tsconfig.base.json
root: true
rules:
  comma-style: error
  comma-dangle: [
    error,
    {
      arrays: "always-multiline",
      objects: "always-multiline",
      imports: "always-multiline",
      exports: "always-multiline",
      functions: "always-multiline",
    },
  ]
  eol-last: [ error, always ]
  import/no-duplicates: error
  import/order: [
    error,
    {
      alphabetize: { order: asc },
      groups: [ builtin, external, parent, sibling ],
      newlines-between: always
    },
  ]
  indent: [ error, 2, { SwitchCase: 1 } ]
  key-spacing: [ error, {mode: minimum } ]
  keyword-spacing: error
  no-constant-condition: error
  prefer-const: error
  quotes: [ error, "double", { allowTemplateLiterals: true, avoidEscape: true } ]
  semi: error
  semi-spacing: error
  spaced-comment: error